name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Pint Check
        run: ./vendor/bin/pint --parallel --test

      - name: Rector Check
        run: ./vendor/bin/rector --dry-run

      - name: ESLint Check
        run: npm run lint:check

      - name: Prettier Check
        run: npm run format:check

      - name: TypeScript Check
        run: npm run types:check

      - name: PHPStan
        run: ./vendor/bin/phpstan --memory-limit=512M
